[lang.en] 
title = "Component of Learning Server for Theoretical Computer Science - NP-complete problems 2"
and = "&"
bachelor-thesis = "Bachelor Thesis"
master-thesis = "Diploma Thesis"
phd-thesis = "PhD Thesis"
supervisor = "Supervisor"
section-supplement = "Chapter"
bibliography = "Bibliography"
conclusion = "Conclusion"
abstract = "Abstract"
keywords = "Keywords"
list-of-symbols = "List of symbols and abbreviations"
outline = "Outline"
acknowledgements = "Acknowledgements"
intro = "Intro"
appendix = "Appendix"
appendices = "Appendices"
list-of-figures = "List of Figures"
list-of-tables = "List of Tables"
list-of-algorithms = "List of Algorithms"
list-of-listings = "List of Listings"
listing-supplement = "Listing"
appendix-supplement = "Appendix"

[lang.cs] 
title = "Komponenta výukového serveru TI - NP-úplné problémy 2"
and = "&"
bachelor-thesis = "Bakalářská práce"
master-thesis = "Diplomová práce"
phd-thesis = "Disertační práce"
supervisor = "Vedoucí práce"
section-supplement = "Kapitola"
bibliography = "Literatura"
conclusion = "Závěr"
abstract = "Abstrakt"
keywords = "Klíčová slova"
list-of-symbols = "Seznam použitých zkratek a symbolů"
outline = "Obsah"
acknowledgements = "Poděkování"
intro = "Úvod"
appendix = "Příloha"
appendices = "Přílohy"
list-of-figures = "Seznam obrázků"
list-of-tables = "Seznam tabulek"
list-of-algorithms = "Seznam algoritmů"
list-of-listings = "Seznam výpisů"
listing-supplement = "Výpis"
appendix-supplement = "Příloha"
